#ifndef CATL_EXIT_STATUS_H
#define CATL_EXIT_STATUS_H

typedef enum {
  CATL_STATUS_OK,
  CATL_STATUS_UNDEFINED_ERROR,
  CATL_STATUS_FAILED_TO_ALLOCATE_MEMORY,
  CATL_STATUS_NULL_POINTER,
  CATL_STATUS_ALREADY_INITIALIZED,
  CATL_STATUS_OUT_OF_RANGE,
  CATL_STATUS_OVERFLOW,
  CATL_STATUS_UNDERFLOW,
  CATL_STATUS_INVALID_VALUE,
  CATL_STATUS_INVALID_STATE,
  CATL_STATUS_EMPTY_LIST,
  CATL_STATUS_CANNOT_FIND,
  CATL_STATUS_LIMIT_EXCEEDED
} CatlExitStatus;

#endif // !CATL_EXIT_STATUS_H
