#ifndef CATL_EXIT_STATUS_H
#define CATL_EXIT_STATUS_H

typedef enum {
  CATL_STATUS_OK = 0,
  CATL_STATUS_UNDEFINED_ERROR = 1,
  CATL_STATUS_FAILED_TO_ALLOCATE_MEMORY = 2,
  CATL_STATUS_NULL_POINTER = 3,
  CATL_STATUS_ALREADY_INITIALIZED = 4,
  CATL_STATUS_OUT_OF_RANGE = 5,
  CATL_STATUS_OVERFLOW = 6,
  CATL_STATUS_INVALID_VALUE = 7,
  CATL_STATUS_EMPTY_LIST = 8,
  CATL_STATUS_CANNOT_FIND = 9,
  CATL_STATUS_LIMIT_EXCEEDED = 10
} CatlExitStatus;

#endif // !CATL_EXIT_STATUS_H
