#ifndef CATL_EXIT_STATUS_H
#define CATL_EXIT_STATUS_H

typedef enum {
  CATL_STATUS_OK = 0,
  CATL_STATUS_UNDEFINED_ERROR = 1,
  CATL_STATUS_FAILED_TO_ALLOCATE_MEMORY = 2,
  CATL_STATUS_INVALID_POSITION = 3,
  CATL_STATUS_INVALID_MEMORY = 4,
  CATL_STATUS_OVERFLOW = 5
} CatlExitStatus;

#endif // !CATL_EXIT_STATUS_H
